name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: $GITHUB_WORKSPACE
          container_name: abc
          account_name: azureserverstart
          sas_token: "sp=racwdli&st=2024-07-02T10:51:31Z&se=2024-07-02T18:51:31Z&spr=https&sv=2022-11-02&sr=c&sig=FKM1eWbbbbWVBeMVBNhnOlJAUgdzsFSXDCQW5oPASr4%3D"
          extra_args: '--destination-path ${{ $GITHUB_SHA }}'
