name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: /
          container_name: abc
          account_name: azureserverstart
          connection_string: ${{ secrets.AZURE_STORAGE_KEY }}
          extra_args: '--destination-path $GITHUB_SHA'
